const nw = window.nightwave;
const app = document.getElementById('app');
const A='../assets/memes/';
const assets={peter:A+'peter.png',pug:A+'pug.png',squirrel:A+'squirrel.png',troll:A+'troll.png'};
const PRESETS={FLAT:[0,0,0,0,0,0,0,0,0,0],BASS:[7,6,4,2,0,0,0,0,0,0],VOCAL:[-2,-1,0,2,4,4,3,1,0,-1],NIGHT:[4,3,1,0,-1,0,1,2,3,4]};
const FREQS=['60','170','310','600','1k','3k','6k','12k','14k','16k'];
let page='home', config={favorites:[],history:[],eqGains:Array(10).fill(0),eqEnabled:true,volume:.82,globalHotkeys:true}, auth={loggedIn:false}, engine={ready:false,status:'connecting'}, now={title:'',artist:'',url:'',artwork:'',position:0,duration:0,playing:false}, searchResults=[], searching=false, queue=JSON.parse(localStorage.getItem('nightwave-queue')||'[]');

const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>{n=Math.max(0,Math.floor(Number(n)||0));return `${Math.floor(n/60)}:${String(n%60).padStart(2,'0')}`};
const saveQueue=()=>localStorage.setItem('nightwave-queue',JSON.stringify(queue));
function toast(t){const e=document.createElement('div');e.className='toast';e.textContent=t;document.body.appendChild(e);setTimeout(()=>e.remove(),2200)}
function isFav(t){return !!t?.url&&(config.favorites||[]).some(x=>x.url===t.url)}
async function save(p){config=await nw.patchConfig(p);render();}
function current(){return now.title?{title:now.title,artist:now.artist,url:now.url,artwork:now.artwork,duration:now.duration}:null}
function setPage(p){page=p;render();}
function toggleFav(t){if(!t?.url)return;const list=[...(config.favorites||[])];const i=list.findIndex(x=>x.url===t.url);if(i>=0)list.splice(i,1);else list.unshift(t);save({favorites:list.slice(0,120)});if(t.url===now.url)nw.control('like');}
function addQueue(t){if(!t?.url)return;queue.push(t);saveQueue();toast('Добавлено в очередь.');render();}
function next(){if(queue.length){const t=queue.shift();saveQueue();nw.control('play-url',t.url);render();}else nw.control('next');}
function trackByUrl(url){return searchResults.find(x=>x.url===url)||(config.favorites||[]).find(x=>x.url===url)||(config.history||[]).find(x=>x.url===url)||queue.find(x=>x.url===url)||(now.url===url?current():null)}

function shell(){
  app.innerHTML=`<div class="nw"><header class="top"><div class="brand">NIGHTWAVE</div><nav class="nav">${['home','search','library','eq','settings'].map(p=>`<button data-nav="${p}" class="${page===p?'on':''}">${p}</button>`).join('')}</nav><div class="win"><button data-win="min">—</button><button data-win="max">□</button><button class="close" data-win="close">×</button></div></header><main class="main">${mainHtml()}</main>${playerHtml()}</div>`;
  bind();
}
function mainHtml(){if(page==='home')return home();if(page==='search')return search();if(page==='library')return library();if(page==='eq')return eq();return settings();}
function home(){const art=now.artwork||assets.peter;const st=engine.ready?'SoundCloud ready':engine.status==='error'?'SoundCloud unavailable':'SoundCloud подключается…';return `<section class="hero"><div class="hero-copy"><div class="eyebrow">SoundCloud desktop client</div><h1><span>${auth.loggedIn?'Твоя':'Музыка.'}</span><span>${auth.loggedIn?'музыка.':'Без'}</span><span>${auth.loggedIn?'Без лишнего.':'лишнего.'}</span></h1><p>Свой интерфейс, настоящий SoundCloud под капотом, очередь, история, 10-полосный EQ и нормальные бинды.</p>${auth.loggedIn?`<div class="status-card connected"><img src="${assets.pug}"><div><strong>SoundCloud подключён.</strong><small>Сессия хранится локально. Никаких Client ID и API Secret.</small></div></div>`:`<button class="status-card" id="login"><img src="${assets.pug}"><div><strong>Войти через SoundCloud</strong><small>Откроется официальный SoundCloud. Пароль вводится только там.</small></div><span class="arrow">→</span></button>`}<div class="engine"><span class="dot ${engine.ready?'ready':engine.status==='error'?'error':''}"></span>${esc(st)}</div><p class="hero-note">Nightwave теперь открывается сразу. SoundCloud грузится отдельно в фоне и больше не может оставить тебя на чёрном экране.</p></div><div class="hero-art"><img class="hero-main-art" src="${esc(art)}"><img class="sticker one" src="${assets.troll}"><img class="sticker two" src="${assets.squirrel}">${now.title?`<div class="now-badge"><span>Now playing</span><strong>${esc(now.title)}</strong><small>${esc(now.artist)}</small></div>`:''}</div></section>`}
function search(){return `<section class="page"><div class="page-head"><h2>ПОИСК.</h2><p>Результаты берутся из SoundCloud через фоновый движок. Интерфейс остаётся полностью Nightwave.</p></div><form class="search-box" id="search-form"><input id="query" autocomplete="off" placeholder="track or artist"><button>${searching?'Ищу…':'Найти'}</button></form><div class="result-head"><span>#</span><span>Track</span><span>Artist</span><span></span></div><div class="results">${results(searchResults,searching?'Ищу в SoundCloud…':'Напиши запрос сверху.')}</div></section>`}
function results(items,empty){if(!items.length)return `<div class="empty"><div><img src="${assets.squirrel}"><h3>${esc(empty)}</h3><p>${engine.ready?'SoundCloud движок готов.':'Движок ещё подключается; интерфейс при этом уже работает.'}</p></div></div>`;return items.map((t,i)=>`<div class="track" data-url="${esc(t.url)}"><div class="index">${String(i+1).padStart(2,'0')}</div><div class="track-main"><img src="${esc(t.artwork||assets.pug)}"><div><div class="track-title">${esc(t.title)}</div><div class="muted">${esc((t.url||'').replace('https://soundcloud.com/',''))}</div></div></div><div class="artist">${esc(t.artist||'SoundCloud')}</div><div class="row-actions"><button class="row-btn" data-act="fav">${isFav(t)?'♥':'♡'}</button><button class="row-btn" data-act="queue">＋</button><button class="row-btn" data-act="play">▶</button></div></div>`).join('')}
function list(items,empty){return items?.length?`<div class="results">${results(items,'')}</div>`:`<div class="empty"><div><img src="${assets.pug}"><h3>${esc(empty)}</h3><p>Треки появятся здесь автоматически.</p></div></div>`}
function library(){const f=config.favorites||[],h=config.history||[];return `<section class="page"><div class="page-head"><h2>МЕДИАТЕКА.</h2><p>Избранное хранится локально. История обновляется автоматически.</p></div><div class="library-section"><div class="section-title"><h3>Избранное</h3><span>${f.length} tracks</span></div>${list(f,'Пока пусто.')}</div><div class="library-section"><div class="section-title"><h3>История</h3><span>${h.length} recent</span></div>${list(h.slice(0,40),'История пока пустая.')}</div></section>`}
function eq(){const g=Array.isArray(config.eqGains)&&config.eqGains.length===10?config.eqGains:Array(10).fill(0);return `<section class="page"><div class="page-head"><h2>ЭКВАЛАЙЗЕР.</h2><p>10 полос от 60 Hz до 16 kHz. Настройки применяются к фоновому SoundCloud движку.</p></div><div class="eq-wrap"><div class="eq-card"><div class="eq-grid">${g.map((v,i)=>`<div class="band"><span class="val" id="v${i}">${Number(v).toFixed(1)}</span><input class="eqs" data-i="${i}" type="range" min="-12" max="12" step="0.5" value="${v}"><label>${FREQS[i]}</label></div>`).join('')}</div></div><aside class="eq-side"><div class="mono-card"><h3>10 bands.</h3><p>Без цветных ручек и лишней графики.</p><div class="switch"><span>EQ enabled</span><input id="eq-enabled" type="checkbox" ${config.eqEnabled!==false?'checked':''}></div><div class="preset">${Object.keys(PRESETS).map(p=>`<button data-preset="${p}">${p}</button>`).join('')}</div></div></aside></div></section>`}
function settings(){return `<section class="page"><div class="page-head"><h2>НАСТРОЙКИ.</h2><p>Только пользовательские настройки. Никаких Client ID, Secret и dev-полей.</p></div><div class="settings"><div class="mono-card"><h3>SoundCloud.</h3><p>${auth.loggedIn?'Сессия подключена.':'Сессия не подключена.'}</p><div class="button-line">${auth.loggedIn?`<button class="plain-btn danger" id="logout">Выйти</button>`:`<button class="plain-btn" id="login2">Войти через SoundCloud</button>`}</div></div><div class="mono-card"><h3>Движок.</h3><p>${engine.ready?'Готов к воспроизведению.':engine.status==='error'?'Не удалось подключиться к SoundCloud.':'Подключается в фоне…'}</p></div><div class="mono-card wide"><h3>Бинды.</h3><div class="kbd-grid">${[['Space','Play / Pause'],['Ctrl + K','Search'],['← / →','Seek 5 sec'],['Ctrl + ← / →','Prev / Next'],['↑ / ↓','Volume'],['M','Mute'],['L','Favorite'],['E','EQ']].map(x=>`<div class="kbd"><span>${x[1]}</span><b>${x[0]}</b></div>`).join('')}</div></div></div></section>`}
function playerHtml(){return `<footer class="player"><div class="p-track"><img src="${esc(now.artwork||assets.squirrel)}"><div><div class="p-title">${esc(now.title||'Nothing playing')}</div><div class="p-artist">${esc(now.artist||'Find something on SoundCloud')}</div></div><button class="heart ${isFav(current())?'on':''}" id="heart">${isFav(current())?'♥':'♡'}</button></div><div class="p-center"><div class="transport"><button data-ctl="prev">│◀</button><button class="play" data-ctl="playpause">${now.playing?'Ⅱ':'▶'}</button><button data-ctl="next">▶│</button></div><div class="timeline"><span>${fmt(now.position)}</span><input id="seek" type="range" min="0" max="1000" value="${now.duration?Math.round(now.position/now.duration*1000):0}"><span>${fmt(now.duration)}</span></div></div><div class="tools"><button class="tool-btn" id="queue">Queue <span>${queue.length}</span></button><button class="tool-btn" data-nav="eq">EQ</button><span class="vol-icon">VOL</span><input class="volume" id="vol" type="range" min="0" max="1" step="0.01" value="${config.volume??.82}"></div></footer>`}

function bind(){
 document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>setPage(b.dataset.nav));document.querySelectorAll('[data-win]').forEach(b=>b.onclick=()=>b.dataset.win==='min'?nw.minimize():b.dataset.win==='max'?nw.maximize():nw.close());
 document.querySelectorAll('[data-ctl]').forEach(b=>b.onclick=()=>b.dataset.ctl==='next'?next():nw.control(b.dataset.ctl));
 document.getElementById('login')?.addEventListener('click',()=>nw.openLogin());document.getElementById('login2')?.addEventListener('click',()=>nw.openLogin());document.getElementById('logout')?.addEventListener('click',async()=>{await nw.logout();auth={loggedIn:false};render()});
 document.getElementById('heart')?.addEventListener('click',()=>{const t=current();if(t)toggleFav(t)});document.getElementById('seek')?.addEventListener('input',e=>nw.control('seek-to',Number(e.target.value)/1000));document.getElementById('vol')?.addEventListener('input',e=>{const v=Number(e.target.value);config.volume=v;nw.control('volume',v);nw.patchConfig({volume:v})});
 document.getElementById('search-form')?.addEventListener('submit',async e=>{e.preventDefault();const q=document.getElementById('query').value.trim();if(!q)return;searching=true;render();searchResults=await nw.search(q);searching=false;render()});
 document.querySelectorAll('.track').forEach(r=>r.ondblclick=()=>{const t=trackByUrl(r.dataset.url);if(t)nw.control('play-url',t.url)});document.querySelectorAll('[data-act]').forEach(b=>b.onclick=e=>{e.stopPropagation();const t=trackByUrl(b.closest('.track')?.dataset.url);if(!t)return;b.dataset.act==='play'?nw.control('play-url',t.url):b.dataset.act==='queue'?addQueue(t):toggleFav(t)});
 document.getElementById('eq-enabled')?.addEventListener('change',e=>{config.eqEnabled=e.target.checked;nw.setEq(config.eqEnabled,config.eqGains);nw.patchConfig({eqEnabled:config.eqEnabled})});document.querySelectorAll('.eqs').forEach(s=>s.oninput=e=>{const i=Number(e.target.dataset.i);config.eqGains[i]=Number(e.target.value);document.getElementById('v'+i).textContent=Number(e.target.value).toFixed(1);nw.setEq(config.eqEnabled!==false,config.eqGains);nw.patchConfig({eqGains:config.eqGains})});document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{config.eqGains=PRESETS[b.dataset.preset].slice();nw.setEq(config.eqEnabled!==false,config.eqGains);nw.patchConfig({eqGains:config.eqGains});render()});
}
function render(){shell()}

window.addEventListener('keydown',e=>{const typing=['INPUT','TEXTAREA'].includes(document.activeElement?.tagName);if(e.ctrlKey&&e.key.toLowerCase()==='k'){e.preventDefault();setPage('search');return}if(typing)return;if(e.code==='Space'){e.preventDefault();nw.control('playpause')}else if(e.key==='ArrowLeft'){e.preventDefault();e.ctrlKey?nw.control('prev'):nw.control('seek-relative',-5)}else if(e.key==='ArrowRight'){e.preventDefault();e.ctrlKey?next():nw.control('seek-relative',5)}else if(e.key==='ArrowUp'){e.preventDefault();config.volume=Math.min(1,(config.volume??.82)+.05);nw.control('volume',config.volume);nw.patchConfig({volume:config.volume});render()}else if(e.key==='ArrowDown'){e.preventDefault();config.volume=Math.max(0,(config.volume??.82)-.05);nw.control('volume',config.volume);nw.patchConfig({volume:config.volume});render()}else if(e.key.toLowerCase()==='m'){e.preventDefault();nw.control('mute')}else if(e.key.toLowerCase()==='l'){const t=current();if(t)toggleFav(t)}else if(e.key.toLowerCase()==='e'){setPage('eq')}});

nw.onNowPlaying(d=>{now={...now,...d};render()});nw.onEngine(d=>{engine=d||engine;render()});nw.onAuth(d=>{auth=d||auth;render()});
render();
(async()=>{config=await nw.getConfig();auth=await nw.authStatus();engine=await nw.engineStatus();render()})();
